### ISSUE TITLE
Hiding access tokens

### ISSUE THREAD

**Issue by HemantKumar01** [WebDevSimplified/Alan-AI-Ecommerce#1]
Github allows .env files to be viewed, and all of the api keys used in this repo are easily accessible. So is there a way to hide them from others or the only way is to remove them?

**Comment by kdgyimah** [comment]
@HemantKumar01  You can and should add those filenames to the .gitignore file in your own project. No need to remove them from the project folder to hide it from others.

You can add these lines to the .gitignore file (or whatever filename(s) you have used for your .env files) and you should be fine.
`.env`
`.env.development`

I think him adding the API keys to this particular project would allow us to test and take advantage of his API Credits, which is thoughtful unless it was an oversight?

**Comment by kdgyimah** [comment]
@HemantKumar01  You can and should add those filenames to the .gitignore file in your own project. No need to remove them from the project folder to hide it from others.

You can add these lines to the **.gitignore** file (or whatever filename(s) you have used for your .env files) and you should be fine.
`.env`
`.env.development`

I think he adding the API keys to this particular project would allow us to test and take advantage of his API Credits, which is thoughtful unless it was an oversight?

**Comment by HemantKumar01** [comment]
Thanks for the reply By the way I have a doubt about security of mozilla firefox browser. Where can I talk to you? I just need 5 minutes
